### ISSUE TITLE
Component Checklist templet

### ISSUE THREAD

**Issue by krvikash35** [krvikash35/react-ui-component#17]
- [ ] **testable** : i.e use js `onMouseEnter`  & `onMouseLeave` instead of `:hover` as hover is not testable in [cypress](https://docs.cypress.io/api/commands/hover.html#Workarounds). accept `data-testid` props for test automation.

- [ ] should forward ref and use shared ref

- [ ] **accessible**: through keyboard(arrow, tab, focus), mouse(hover), screen reader(aria)

- [ ] **themeable**: i.e should accept colorScheme, 

- [ ] **customisable**: i.e `Button` should accept `style`, `classNames` etc for customization

- [ ] should expose child component instead of hiding it i.e export `Table.Row` instead of just on `Table` component.

- [ ] **maintainable**: code should be maintainable

- [ ] **motion**: should have proper animatin and transition whereever it is required.

- [ ] **responsive**: should respond appropriatly with screen size. use `mediaQuery` or responsive layout/unit like `flex`, `grid`, `50vw` etc or use relative unit like `rem`
